package symbol

// CONSTANT_CLASS_TAG The tag value of CONSTANT_Class_info JVMS structures.
var CONSTANT_CLASS_TAG = 7

// CONSTANT_FIELDREF_TAG The tag value of CONSTANT_Fieldref_info JVMS structures.
var CONSTANT_FIELDREF_TAG = 9

var CONSTANT_METHODREF_TAG = 10
var CONSTANT_INTERFACE_METHODREF_TAG = 11
var CONSTANT_STRING_TAG = 8
var CONSTANT_INTEGER_TAG = 3
var CONSTANT_FLOAT_TAG = 4
var CONSTANT_LONG_TAG = 5
var CONSTANT_DOUBLE_TAG = 6
var CONSTANT_NAME_AND_TYPE_TAG = 12
var CONSTANT_UTF8_TAG = 1
var CONSTANT_METHOD_HANDLE_TAG = 15
var CONSTANT_METHOD_TYPE_TAG = 16
var CONSTANT_INVOKE_DYNAMIC_TAG = 18
var CONSTANT_MODULE_TAG = 19
var CONSTANT_PACKAGE_TAG = 20
var BOOTSTRAP_METHOD_TAG = 64
var TYPE_TAG = 128
var UNINITIALIZED_TYPE_TAG = 129
var MERGED_TYPE_TAG = 130
