package symbol

// CONSTANT_CLASS_TAG The tag value of CONSTANT_Class_info JVMS structures.
const CONSTANT_CLASS_TAG = 7
const CONSTANT_FIELDREF_TAG = 9
const CONSTANT_METHODREF_TAG = 10
const CONSTANT_INTERFACE_METHODREF_TAG = 11
const CONSTANT_STRING_TAG = 8
const CONSTANT_INTEGER_TAG = 3
const CONSTANT_FLOAT_TAG = 4
const CONSTANT_LONG_TAG = 5
const CONSTANT_DOUBLE_TAG = 6
const CONSTANT_NAME_AND_TYPE_TAG = 12
const CONSTANT_UTF8_TAG = 1
const CONSTANT_METHOD_HANDLE_TAG = 15
const CONSTANT_METHOD_TYPE_TAG = 16
const CONSTANT_INVOKE_DYNAMIC_TAG = 18
const CONSTANT_MODULE_TAG = 19
const CONSTANT_PACKAGE_TAG = 20
const BOOTSTRAP_METHOD_TAG = 64
const TYPE_TAG = 128
const UNINITIALIZED_TYPE_TAG = 129
const MERGED_TYPE_TAG = 130
